# 代表使用 docker-compose 项目的版本号
version: '3.8'

# 管理一组服务
services:
    # 服务名称
    tomcat:
        # 给当前容器指定一个名称，不推荐手动指定，防止出现命名冲突
        container_name: tomcat01
        # 代表使用哪个镜像，类似于 docker run 指定的镜像名称
        image: tomcat:8.0
        # 代表宿主机和容器中端口映射，类似于 docker run -p 参数
        ports:
            - 8080:8080

    redis:
        image: redis:5.0.12
        ports:
            - 6379:6379

    mysql:
        image: mysql:5.6
        ports:
            - '3306:3306'
        # 代表给当前容器启动指定环境 
        environment:
            - 'MYSQL_ROOT_PASSWORD=root'
        # 代表给当前容器和宿主机指定数据卷
        volumes:
            - /root/docker/docker-test/mysql:/var/lib/mysql

